### ISSUE TITLE
Updating publications

### ISSUE THREAD

**Issue by marthawhite** [rlai-lab/rlai-lab.github.io#5]
It seems worthwhile to have an up-to-date list of publications for RLAI. But, this will be a long list, and maybe onerous to maintain. Any suggestions about how to display this, or if we should just remove it, would be good.

**Comment by Kongaloosh** [comment]
Publications as in "you should read these", or publications as in "here is what's hot off the press in the group"? If it's the latter, one thing which could be done is just have a file that people can PR to which has a link to the file, the citation, and maybe a few tags. It could be a JSON. 

Jekyll (I think) uses jinja, which means we could do something like this:

```
{% for pub in site.data.publications %}
  <p>
    <a href={{pub.file}}">
      {{pub.citation}}
    </a>
  </p>
  <hr>
{% endfor %}
```

Which would produce a list of publications which are clickable links directing to the file. Whenever the data gets updated, it would change the site automatically. Jekyll has more info on how this works [here](https://jekyllrb.com/docs/datafiles/)

**Comment by Kongaloosh** [comment]
Ah, I just looked at the template and realized that this templating is effectively what's already being done. Sorry.

**Comment by marthawhite** [comment]
I like your solution a lot better. I've changed it to use data files. My solution was just a start, and was ugly since you still had to write html. 

And they should be our publications. Under resources, we could consider making a list of people's favourite papers.

**Comment by andnp** [comment]
I will note that you _could_ get the same effect as the original list using pure markdown (and no html).

For instance:
```html
<ul>
 <li>An Off-policy Policy Gradient Theorem Using Emphatic Weightings.
  Ehsan Imani, Eric Graves and Martha White.
  <i>Advances in Neural Information Processing Systems (NIPS)</i>,
    2018. <a href="https://arxiv.org/abs/1811.09013">[pdf]</a>
    </li>
    <br />
</ul>
```
would become
```markdown
* An Off-policy Policy Gradient Theorem Using Emphatic Weightings.
  Ehsan Imani, Eric Graves and Martha White. _Advances in Neural Information Processing Systems (NIPS)_, 2018 [[pdf]](https://arxiv.org/abs/1811.09013)
```
and both should render equivalently.

**Comment by andnp** [comment]
That said, I definitely prefer the yaml way. Are the files contained in `rlai_collections` now no longer needed?

**Comment by marthawhite** [comment]
Yes, that was my mistake when starting this. You should be able to remove all of that, and just use yaml files in _data.
