### ISSUE TITLE
List of TODOs/wants

### ISSUE THREAD

**Issue by mkschleg** [rlai-lab/rlai-lab.github.io#6]
Is there a list of things that need to be done for the website? Or are we mostly going adhoc?

**Comment by mkschleg** [comment]
Although it seems like the issues might be fulfilling this.

**Comment by Kongaloosh** [comment]
I think maybe we could bring this up on slack to on-board more people and get some PRs in. If it's more of a 'community gardening' project, rather than the sole responsibility of a handful of people, it'll be far more sustainable.

**Comment by marthawhite** [comment]
Yes let's open it up. Please go ahead Alex.

**Comment by Kongaloosh** [comment]
I've pinged the slack; hopefully we start a discussion there.
